---
- hosts: all
  module_defaults:
    ansible.builtin.file:
       pip: pip3
       python: python3
  become: true
  tasks:
      - name: Update Repository Index
        apt:
          update_cache: yes
        when: ansible_distribution in ["Debian", "Ubuntu"]

      - name: Install python3, pip3, and Java open-jdk (CentOS)
        dnf:
          name:
             - python3
             - python3-pip
             - java-1.8.0-openjdk
          state: latest
        when: ansible_distribution == "CentOS"

      - name: Install python3, pip3, and Java open-jdk (Ubuntu)
        apt:
          name:
             - python3
             - pip
             - openjdk-8-jdk
          state: latest
        when: ansible_distribution == "Ubuntu"

      - name: MOTD Banner
        copy:
          dest: /etc/motd
          content: "Ansible Managed node by junemel\n"


